version: 2

builds:
  - id: "uptickd-darwin"
    main: ./cmd/uptickd
    binary: bin/uptickd
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
    goos:
      - darwin
    goarch:
      - amd64
    flags:
        - -tags=cgo,ledger
    ldflags:
      - -s -w -X github.com/cosmos/cosmos-sdk/version.Name=uptick -X github.com/cosmos/cosmos-sdk/version.AppName=uptickd -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}} -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}} -X github.com/UptickNetwork/uptick/version.AppVersion={{.Version}} -X github.com/UptickNetwork/uptick/version.GitCommit={{.Commit}}
  - id: "uptickd-darwin-arm64"
    main: ./cmd/uptickd
    binary: bin/uptickd
    env:
      - CGO_ENABLED=1
      - CC=oa64-clang
      - CXX=oa64-clang++
    goos:
      - darwin
    goarch:
      - arm64
    flags:
      - -tags=cgo,ledger
    ldflags:
      - -s -w -X github.com/cosmos/cosmos-sdk/version.Name=uptick -X github.com/cosmos/cosmos-sdk/version.AppName=uptickd -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}} -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}} -X github.com/UptickNetwork/uptick/version.AppVersion={{.Version}} -X github.com/UptickNetwork/uptick/version.GitCommit={{.Commit}}
  - id: "uptickd-linux"
    main: ./cmd/uptickd
    binary: bin/uptickd
    env:
      - CGO_ENABLED=1
      - CC=gcc
      - CXX=g++
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -tags=cgo,ledger
    ldflags:
      - -s -w -X github.com/cosmos/cosmos-sdk/version.Name=uptick -X github.com/cosmos/cosmos-sdk/version.AppName=uptickd -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}} -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}} -X github.com/UptickNetwork/uptick/version.AppVersion={{.Version}} -X github.com/UptickNetwork/uptick/version.GitCommit={{.Commit}}
  - id: "uptickd-linux-arm64"
    main: ./cmd/uptickd
    binary: bin/uptickd
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    goos:
      - linux
    goarch:
      - arm64
    flags:
      - -tags=cgo,ledger
    ldflags:
      - -s -w -X github.com/cosmos/cosmos-sdk/version.Name=uptick -X github.com/cosmos/cosmos-sdk/version.AppName=uptickd -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}} -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}} -X github.com/UptickNetwork/uptick/version.AppVersion={{.Version}} -X github.com/UptickNetwork/uptick/version.GitCommit={{.Commit}}
archives:
- name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
  ids:
  - uptickd-darwin
  - uptickd-darwin-arm64
  - uptickd-linux
  - uptickd-linux-arm64
  
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
snapshot:
  version_template: "{{ .Tag }}-next"
