version: 1
build:
  binary: uptickd
  proto:
    path: proto
    third_party_paths:
    - third_party/proto
    - proto_vendor
accounts:
- name: alice
  coins:
  - 100000000uatom
  - 100000000000000000000auptick
- name: bob
  coins:
  - 5000000000000auptick
faucet:
  name: bob
  coins:
  - 10auptick
  host: 0.0.0.0:4500
genesis:
  app_state:
    crisis:
      constant_fee:
        denom: auptick
    evm:
      params:
        evm_denom: auptick
    gov:
      deposit_params:
        min_deposit:
        - amount: "10000000"
          denom: auptick
    mint:
      params:
        mint_denom: auptick
    staking:
      params:
        bond_denom: auptick
  chain_id: uptick_7777-1
validators:
- name: alice
  bonded: 100000000000000000000auptick
  app:
    evm-rpc:
      address: 0.0.0.0:8545
      ws-address: 0.0.0.0:8546
  home: $HOME/.uptickd
