version: '3'

services:
  node0:
    container_name: upticknode0
    image: "uptick/node:v0.1"
    ports:
      - "26656-26657:26656-26657"
    volumes:
      - ./localnet-setup/node0/uptickd:/data-dir
    command:
      - /start-docker.sh
    networks:
      localnet:
        ipv4_address: 192.167.10.2

  node1:
    container_name: upticknode1
    image: "uptick/node:v0.1"
    ports:
      - "26659-26660:26656-26657"
    volumes:
      - ./localnet-setup/node1/uptickd:/data-dir
    command:
      - /start-docker.sh
    networks:
      localnet:
        ipv4_address: 192.167.10.3

  node2:
    container_name: upticknode2
    image: "uptick/node:v0.1"
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./localnet-setup/node2/uptickd:/data-dir
    command:
      - /start-docker.sh
    networks:
      localnet:
        ipv4_address: 192.167.10.4

  node3:
    container_name: upticknode3
    image: "uptick/node:v0.1"
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./localnet-setup/node3/uptickd:/data-dir
    command:
      - /start-docker.sh
    networks:
      localnet:
        ipv4_address: 192.167.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.167.10.0/16