// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: uptick/evm_ibc/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	types "github.com/cosmos/ibc-go/v8/modules/core/02-client/types"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgTransferERC721 defines a message to transfer ERC721 tokens between chains via IBC
// It contains information about the token contract, token IDs, source and destination of the transfer,
// timeout parameters and optional memo
type MsgTransferERC721 struct {
	EvmContractAddress string `protobuf:"bytes,1,opt,name=evm_contract_address,json=evmContractAddress,proto3" json:"evm_contract_address,omitempty"`
	// tokenID to convert
	EvmTokenIds []string `protobuf:"bytes,2,rep,name=evm_token_ids,json=evmTokenIds,proto3" json:"evm_token_ids,omitempty"`
	// the port on which the packet will be sent
	SourcePort string `protobuf:"bytes,3,opt,name=source_port,json=sourcePort,proto3" json:"source_port,omitempty"`
	// the channel by which the packet will be sent
	SourceChannel string `protobuf:"bytes,4,opt,name=source_channel,json=sourceChannel,proto3" json:"source_channel,omitempty"`
	// the class_id of tokens to be transferred
	ClassId string `protobuf:"bytes,5,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	// the non fungible tokens to be transferred
	CosmosTokenIds []string `protobuf:"bytes,6,rep,name=cosmos_token_ids,json=cosmosTokenIds,proto3" json:"cosmos_token_ids,omitempty"`
	// the sender address
	EvmSender string `protobuf:"bytes,7,opt,name=evm_sender,json=evmSender,proto3" json:"evm_sender,omitempty"`
	// the recipient address on the destination chain
	CosmosReceiver string `protobuf:"bytes,8,opt,name=cosmos_receiver,json=cosmosReceiver,proto3" json:"cosmos_receiver,omitempty"`
	// Timeout height relative to the current block height.
	// The timeout is disabled when set to 0.
	TimeoutHeight types.Height `protobuf:"bytes,9,opt,name=timeout_height,json=timeoutHeight,proto3" json:"timeout_height"`
	// Timeout timestamp in absolute nanoseconds since unix epoch.
	// The timeout is disabled when set to 0.
	TimeoutTimestamp uint64 `protobuf:"varint,10,opt,name=timeout_timestamp,json=timeoutTimestamp,proto3" json:"timeout_timestamp,omitempty"`
	// optional memo
	Memo string `protobuf:"bytes,11,opt,name=memo,proto3" json:"memo,omitempty"`
}

func (m *MsgTransferERC721) Reset()         { *m = MsgTransferERC721{} }
func (m *MsgTransferERC721) String() string { return proto.CompactTextString(m) }
func (*MsgTransferERC721) ProtoMessage()    {}
func (*MsgTransferERC721) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa14fc3acb20b637, []int{0}
}
func (m *MsgTransferERC721) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgTransferERC721) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgTransferERC721.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgTransferERC721) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgTransferERC721.Merge(m, src)
}
func (m *MsgTransferERC721) XXX_Size() int {
	return m.Size()
}
func (m *MsgTransferERC721) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgTransferERC721.DiscardUnknown(m)
}

var xxx_messageInfo_MsgTransferERC721 proto.InternalMessageInfo

// MsgTransferERC721Response defines the response type for TransferERC721 RPC
type MsgTransferERC721Response struct {
}

func (m *MsgTransferERC721Response) Reset()         { *m = MsgTransferERC721Response{} }
func (m *MsgTransferERC721Response) String() string { return proto.CompactTextString(m) }
func (*MsgTransferERC721Response) ProtoMessage()    {}
func (*MsgTransferERC721Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa14fc3acb20b637, []int{1}
}
func (m *MsgTransferERC721Response) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgTransferERC721Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgTransferERC721Response.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgTransferERC721Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgTransferERC721Response.Merge(m, src)
}
func (m *MsgTransferERC721Response) XXX_Size() int {
	return m.Size()
}
func (m *MsgTransferERC721Response) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgTransferERC721Response.DiscardUnknown(m)
}

var xxx_messageInfo_MsgTransferERC721Response proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgTransferERC721)(nil), "uptick.evm_ibc.v1.MsgTransferERC721")
	proto.RegisterType((*MsgTransferERC721Response)(nil), "uptick.evm_ibc.v1.MsgTransferERC721Response")
}

func init() { proto.RegisterFile("uptick/evm_ibc/v1/tx.proto", fileDescriptor_fa14fc3acb20b637) }

var fileDescriptor_fa14fc3acb20b637 = []byte{
	// 556 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x31, 0x6f, 0xd3, 0x40,
	0x14, 0xb6, 0x9b, 0xd0, 0x36, 0x17, 0x35, 0x34, 0xa7, 0x0e, 0x6e, 0x00, 0x27, 0x8a, 0x40, 0x58,
	0x40, 0xed, 0x26, 0x0c, 0x95, 0xd8, 0x48, 0x84, 0x68, 0x86, 0x22, 0x64, 0xc2, 0xc2, 0x62, 0x39,
	0xe7, 0x87, 0x73, 0x4a, 0xec, 0xb3, 0xee, 0x2e, 0xa6, 0xac, 0x4c, 0x8c, 0x48, 0x48, 0x8c, 0xa8,
	0x3f, 0xa7, 0x63, 0x05, 0x0b, 0x13, 0x42, 0x09, 0x03, 0x3f, 0x03, 0xf9, 0xce, 0x41, 0x88, 0x2c,
	0x4c, 0x79, 0xf9, 0xbe, 0xef, 0x7d, 0xef, 0xd3, 0xbd, 0x67, 0xd4, 0x5a, 0x64, 0x92, 0x92, 0x99,
	0x07, 0x79, 0x12, 0xd0, 0x09, 0xf1, 0xf2, 0x9e, 0x27, 0xcf, 0xdd, 0x8c, 0x33, 0xc9, 0x70, 0x53,
	0x73, 0x6e, 0xc9, 0xb9, 0x79, 0xaf, 0x75, 0x10, 0xb3, 0x98, 0x29, 0xd6, 0x2b, 0x2a, 0x2d, 0x6c,
	0xdd, 0x8c, 0x19, 0x8b, 0xe7, 0xe0, 0x85, 0x19, 0xf5, 0xc2, 0x34, 0x65, 0x32, 0x94, 0x94, 0xa5,
	0xa2, 0x64, 0xdb, 0x85, 0x2f, 0x61, 0x1c, 0x3c, 0x32, 0xa7, 0x90, 0xca, 0x62, 0x86, 0xae, 0xb4,
	0xa0, 0xfb, 0xa5, 0x82, 0x9a, 0x67, 0x22, 0x1e, 0xf3, 0x30, 0x15, 0xaf, 0x81, 0x3f, 0xf1, 0x87,
	0x27, 0xfd, 0x1e, 0x3e, 0x46, 0x07, 0xc5, 0x60, 0xc2, 0x52, 0xc9, 0x43, 0x22, 0x83, 0x30, 0x8a,
	0x38, 0x08, 0x61, 0x99, 0x1d, 0xd3, 0xa9, 0xf9, 0x18, 0xf2, 0x64, 0x58, 0x52, 0x8f, 0x35, 0x83,
	0xbb, 0x68, 0xaf, 0xe8, 0x90, 0x6c, 0x06, 0x69, 0x40, 0x23, 0x61, 0x6d, 0x75, 0x2a, 0x4e, 0xcd,
	0xaf, 0x43, 0x9e, 0x8c, 0x0b, 0x6c, 0x14, 0x09, 0xdc, 0x46, 0x75, 0xc1, 0x16, 0x9c, 0x40, 0x90,
	0x31, 0x2e, 0xad, 0x8a, 0x32, 0x43, 0x1a, 0x7a, 0xce, 0xb8, 0xc4, 0x77, 0x50, 0xa3, 0x14, 0x90,
	0x69, 0x98, 0xa6, 0x30, 0xb7, 0xaa, 0x4a, 0xb3, 0xa7, 0xd1, 0xa1, 0x06, 0xf1, 0x21, 0xda, 0x25,
	0xf3, 0x50, 0x88, 0x80, 0x46, 0xd6, 0x35, 0x25, 0xd8, 0x51, 0xff, 0x47, 0x11, 0x76, 0xd0, 0x3e,
	0x61, 0x22, 0x61, 0xe2, 0xaf, 0x24, 0xdb, 0x2a, 0x49, 0x43, 0xe3, 0x7f, 0xc2, 0xdc, 0x42, 0xa8,
	0x08, 0x2c, 0x20, 0x8d, 0x80, 0x5b, 0x3b, 0xca, 0xa6, 0x06, 0x79, 0xf2, 0x42, 0x01, 0xf8, 0x2e,
	0xba, 0x5e, 0x1a, 0x71, 0x20, 0x40, 0x73, 0xe0, 0xd6, 0xae, 0xd2, 0x94, 0x3e, 0x7e, 0x89, 0xe2,
	0xa7, 0xa8, 0x21, 0x69, 0x02, 0x6c, 0x21, 0x83, 0x29, 0xd0, 0x78, 0x2a, 0xad, 0x5a, 0xc7, 0x74,
	0xea, 0xfd, 0x96, 0x5b, 0xac, 0xad, 0x78, 0x7a, 0xb7, 0x7c, 0xf0, 0xbc, 0xe7, 0x9e, 0x2a, 0xc5,
	0xa0, 0x7a, 0xf9, 0xbd, 0x6d, 0xf8, 0x7b, 0x65, 0x9f, 0x06, 0xf1, 0x7d, 0xd4, 0x5c, 0x1b, 0x15,
	0xbf, 0x42, 0x86, 0x49, 0x66, 0xa1, 0x8e, 0xe9, 0x54, 0xfd, 0xfd, 0x92, 0x18, 0xaf, 0x71, 0x8c,
	0x51, 0x35, 0x81, 0x84, 0x59, 0x75, 0x95, 0x49, 0xd5, 0x8f, 0x76, 0xdf, 0x5f, 0xb4, 0x8d, 0x5f,
	0x17, 0x6d, 0xa3, 0x7b, 0x03, 0x1d, 0x6e, 0xec, 0xd4, 0x07, 0x91, 0xb1, 0x54, 0x40, 0xff, 0xb3,
	0x89, 0x2a, 0x67, 0x22, 0xc6, 0x9f, 0x4c, 0xd4, 0xf8, 0x67, 0xed, 0xb7, 0xdd, 0x8d, 0xab, 0x73,
	0x37, 0x8c, 0x5a, 0x0f, 0xfe, 0x47, 0xb5, 0x1e, 0xd7, 0x3d, 0x7e, 0xf7, 0xf5, 0xe7, 0xc7, 0xad,
	0x7b, 0xd8, 0xf1, 0xd6, 0xd7, 0xce, 0xc9, 0x49, 0xbf, 0xa7, 0x8f, 0xdd, 0xa3, 0x13, 0x72, 0x24,
	0xcb, 0xc6, 0x23, 0xcd, 0x0c, 0x4e, 0x2f, 0x97, 0xb6, 0x79, 0xb5, 0xb4, 0xcd, 0x1f, 0x4b, 0xdb,
	0xfc, 0xb0, 0xb2, 0x8d, 0xab, 0x95, 0x6d, 0x7c, 0x5b, 0xd9, 0xc6, 0x2b, 0x37, 0xa6, 0x72, 0xba,
	0x98, 0xb8, 0x84, 0x25, 0xde, 0x4b, 0xe5, 0xf6, 0x0c, 0xe4, 0x1b, 0xc6, 0x67, 0x6b, 0xef, 0xf3,
	0xe2, 0x5b, 0x1a, 0x0d, 0x86, 0x9e, 0x7c, 0x9b, 0x81, 0x98, 0x6c, 0xab, 0x1b, 0x7f, 0xf8, 0x3b,
	0x00, 0x00, 0xff, 0xff, 0xf3, 0x70, 0x9a, 0x8c, 0x69, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// TransferERC721 defines a method to transfer ERC721 tokens between chains via IBC
	TransferERC721(ctx context.Context, in *MsgTransferERC721, opts ...grpc.CallOption) (*MsgTransferERC721Response, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) TransferERC721(ctx context.Context, in *MsgTransferERC721, opts ...grpc.CallOption) (*MsgTransferERC721Response, error) {
	out := new(MsgTransferERC721Response)
	err := c.cc.Invoke(ctx, "/uptick.evm_ibc.v1.Msg/TransferERC721", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// TransferERC721 defines a method to transfer ERC721 tokens between chains via IBC
	TransferERC721(context.Context, *MsgTransferERC721) (*MsgTransferERC721Response, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) TransferERC721(ctx context.Context, req *MsgTransferERC721) (*MsgTransferERC721Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferERC721 not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_TransferERC721_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgTransferERC721)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).TransferERC721(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/uptick.evm_ibc.v1.Msg/TransferERC721",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).TransferERC721(ctx, req.(*MsgTransferERC721))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "uptick.evm_ibc.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TransferERC721",
			Handler:    _Msg_TransferERC721_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "uptick/evm_ibc/v1/tx.proto",
}

func (m *MsgTransferERC721) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgTransferERC721) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgTransferERC721) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Memo) > 0 {
		i -= len(m.Memo)
		copy(dAtA[i:], m.Memo)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Memo)))
		i--
		dAtA[i] = 0x5a
	}
	if m.TimeoutTimestamp != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.TimeoutTimestamp))
		i--
		dAtA[i] = 0x50
	}
	{
		size, err := m.TimeoutHeight.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x4a
	if len(m.CosmosReceiver) > 0 {
		i -= len(m.CosmosReceiver)
		copy(dAtA[i:], m.CosmosReceiver)
		i = encodeVarintTx(dAtA, i, uint64(len(m.CosmosReceiver)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.EvmSender) > 0 {
		i -= len(m.EvmSender)
		copy(dAtA[i:], m.EvmSender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.EvmSender)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.CosmosTokenIds) > 0 {
		for iNdEx := len(m.CosmosTokenIds) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.CosmosTokenIds[iNdEx])
			copy(dAtA[i:], m.CosmosTokenIds[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.CosmosTokenIds[iNdEx])))
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.ClassId) > 0 {
		i -= len(m.ClassId)
		copy(dAtA[i:], m.ClassId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ClassId)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.SourceChannel) > 0 {
		i -= len(m.SourceChannel)
		copy(dAtA[i:], m.SourceChannel)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SourceChannel)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.SourcePort) > 0 {
		i -= len(m.SourcePort)
		copy(dAtA[i:], m.SourcePort)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SourcePort)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.EvmTokenIds) > 0 {
		for iNdEx := len(m.EvmTokenIds) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.EvmTokenIds[iNdEx])
			copy(dAtA[i:], m.EvmTokenIds[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.EvmTokenIds[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.EvmContractAddress) > 0 {
		i -= len(m.EvmContractAddress)
		copy(dAtA[i:], m.EvmContractAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.EvmContractAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgTransferERC721Response) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgTransferERC721Response) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgTransferERC721Response) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgTransferERC721) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.EvmContractAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.EvmTokenIds) > 0 {
		for _, s := range m.EvmTokenIds {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	l = len(m.SourcePort)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.SourceChannel)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ClassId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.CosmosTokenIds) > 0 {
		for _, s := range m.CosmosTokenIds {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	l = len(m.EvmSender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.CosmosReceiver)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.TimeoutHeight.Size()
	n += 1 + l + sovTx(uint64(l))
	if m.TimeoutTimestamp != 0 {
		n += 1 + sovTx(uint64(m.TimeoutTimestamp))
	}
	l = len(m.Memo)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgTransferERC721Response) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgTransferERC721) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgTransferERC721: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgTransferERC721: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EvmContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EvmContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EvmTokenIds", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EvmTokenIds = append(m.EvmTokenIds, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourcePort", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourcePort = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceChannel", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceChannel = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClassId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClassId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CosmosTokenIds", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CosmosTokenIds = append(m.CosmosTokenIds, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EvmSender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EvmSender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CosmosReceiver", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CosmosReceiver = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeoutHeight", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TimeoutHeight.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeoutTimestamp", wireType)
			}
			m.TimeoutTimestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TimeoutTimestamp |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Memo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Memo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgTransferERC721Response) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgTransferERC721Response: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgTransferERC721Response: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
