// SPDX-License-Identifier: MIT
// OpenZeppelin Contracts (last updated v4.5.0) (token/ERC721/presets/ERC721PresetMinterPauserAutoId.sol)

pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/token/ERC721/extensions/ERC721Enumerable.sol";
import "@openzeppelin/contracts/token/ERC721/extensions/ERC721Burnable.sol";
import "@openzeppelin/contracts/token/ERC721/extensions/ERC721Pausable.sol";
import "@openzeppelin/contracts/access/AccessControlEnumerable.sol";
import "@openzeppelin/contracts/utils/Context.sol";

/**
 * @dev {ERC721} token, including:
 *
 *  - ability for holders to burn (destroy) their tokens
 *  - a minter role that allows for token minting (creation)
 *  - a pauser role that allows to stop all token transfers
 *  - token ID and URI autogeneration
 *
 * This contract uses {AccessControl} to lock permissioned functions using the
 * different roles - head to its documentation for details.
 *
 * The account that deploys the contract will be granted the minter and pauser
 * roles, as well as the default admin role, which will let it grant both minter
 * and pauser roles to other accounts.
 *
 * _Deprecated in favor of https://wizard.openzeppelin.com/[Contracts Wizard]._
 */
contract ERC721Uptick is
Context,
AccessControlEnumerable,
ERC721Enumerable,
ERC721Burnable,
ERC721Pausable
{
    bytes32 public constant MINTER_ROLE = keccak256("MINTER_ROLE");
    bytes32 public constant PAUSER_ROLE = keccak256("PAUSER_ROLE");
    uint256 public constant MAX_BATCH_SIZE = 100;
    event EnhanceInfoSet(uint256 indexed tokenId, string name, string uri, string uriHash);

    string private _baseTokenURI;

    struct EnhanceNFTInfo{
        string name;
        string uri;
        string data;
        string uriHash;
    }

    struct EnhanceClassInfo{
        string data;
        string description;
        bool mint_restricted;
        string schema;
        bool update_restricted;
        string uri;
        string uri_hash;
    }

    mapping(uint256 => EnhanceNFTInfo) internal _idEnhanceInfoMap;
    EnhanceClassInfo private _enhanceClassInfo;

    /**
     * @dev Grants `DEFAULT_ADMIN_ROLE`, `MINTER_ROLE` and `PAUSER_ROLE` to the
     * account that deploys the contract.
     *
     * Token URIs will be autogenerated based on `baseURI` and their token IDs.
     * See {ERC721-tokenURI}.
     */
    constructor(
        string memory name,
        string memory symbol,
        string memory baseTokenURI,
        string memory data,
        string memory description,
        bool mint_restricted,
        string memory schema,
        bool update_restricted,
        string memory uri_hash

    ) ERC721(name, symbol) {
        _baseTokenURI = baseTokenURI;

        _grantRole(DEFAULT_ADMIN_ROLE, _msgSender());

        _grantRole(MINTER_ROLE, _msgSender());
        _grantRole(PAUSER_ROLE, _msgSender());

        _enhanceClassInfo.data = data;
        _enhanceClassInfo.description = description;
        _enhanceClassInfo.mint_restricted = mint_restricted;
        _enhanceClassInfo.schema = schema;
        _enhanceClassInfo.update_restricted = update_restricted;
        _enhanceClassInfo.uri = baseTokenURI;
        _enhanceClassInfo.uri_hash = uri_hash;

    }



    function _baseURI() internal view virtual override returns (string memory) {
        return _baseTokenURI;
    }

    /**
     * @dev Creates a new token for `to`. Its token ID will be automatically
     * assigned (and available on the emitted {IERC721-Transfer} event), and the token
     * URI autogenerated based on the base URI passed at construction.
     *
     * Uses {ERC721-_safeMint} (audit G-07): `to` comes from a user-supplied EVM
     * receiver in the Cosmos->ERC721 conversion path, so a contract receiver
     * that does not implement {IERC721Receiver-onERC721Received} must fail the
     * call instead of silently locking the token at an address that can never
     * transfer it out. The receiver callback runs *after* the ownership state
     * is written, so a reentrant call observes a consistent token state.
     *
     * See {ERC721-_safeMint}.
     *
     * Requirements:
     *
     * - the caller must have the `MINTER_ROLE`.
     * - `to` must be an EOA or a contract implementing {IERC721Receiver}.
     */
    function mint(address to, uint256 id,string memory uri) public virtual {
        require(
            hasRole(MINTER_ROLE, _msgSender()),
            "ERC721PresetMinterPauserAutoId: must have minter role to mint"
        );
        require(!paused(), "ERC721Pausable: token transfer while paused");
        require(bytes(uri).length <= 256, "ERC721Uptick: uri too long");

        // We cannot just use balanceOf to create the new tokenId because tokens
        // can be burned (destroyed), so we need a separate counter.
        //
        // Effects before interactions: the metadata is committed before
        // _safeMint invokes the receiver hook, so a reentrant tokenURI() read
        // inside onERC721Received never observes the token without its URI. A
        // revert anywhere in _safeMint still rolls the whole EVM call back.
        _idEnhanceInfoMap[id].uri = uri;
        _safeMint(to, id);
    }

    /**
     * @dev Creates a new token for `to`. Its token ID will be automatically
     * assigned (and available on the emitted {IERC721-Transfer} event), and the token
     * URI autogenerated based on the base URI passed at construction.
     *
     * See {ERC721-_safeMint}.
     *
     * Requirements:
     *
     * - the caller must have the `MINTER_ROLE`.
     * - `to` must be an EOA or a contract implementing {IERC721Receiver}.
     */
    function mintEnhance(address to, uint256 id,string memory name,string memory uri,string memory data,string memory uriHash) public virtual {
        require(
            hasRole(MINTER_ROLE, _msgSender()),
            "ERC721PresetMinterPauserAutoId: must have minter role to mint"
        );
        require(!paused(), "ERC721Pausable: token transfer while paused");
        require(bytes(uri).length <= 256, "ERC721Uptick: uri too long");

        // We cannot just use balanceOf to create the new tokenId because tokens
        // can be burned (destroyed), so we need a separate counter.

        _idEnhanceInfoMap[id].name = name;
        _idEnhanceInfoMap[id].uri = uri;
        _idEnhanceInfoMap[id].data = data;
        _idEnhanceInfoMap[id].uriHash = uriHash;
        // _safeMint (audit G-07) runs the IERC721Receiver hook for contract
        // receivers; the metadata above is already committed so a reentrant
        // read sees a fully populated token.
        _safeMint(to, id);
        emit EnhanceInfoSet(id, name, uri, uriHash);
    }

    /**
     * @dev See {IERC721Metadata-tokenURI}.
     */
    function tokenURI(uint256 tokenId) public view virtual override returns (string memory) {

        require(_exists(tokenId), "ERC721Metadata: URI query for nonexistent token");
        return _idEnhanceInfoMap[tokenId].uri;
    }

    /**
     * @dev Creates a new token for `to`. Its token ID will be automatically
     * assigned (and available on the emitted {IERC721-Transfer} event), and the token
     * URI autogenerated based on the base URI passed at construction.
     *
     * See {ERC721-_safeMint}.
     *
     * Requirements:
     *
     * - the caller must have the `MINTER_ROLE`.
     * - `to` must be an EOA or a contract implementing {IERC721Receiver}; a
     *   rejecting receiver reverts the whole batch.
     */
    function mintBatch(address to, uint256[] memory ids) public virtual {
        require(
            hasRole(MINTER_ROLE, _msgSender()),
            "ERC721PresetMinterPauserAutoId: must have minter role to mint"
        );
        require(!paused(), "ERC721Pausable: token transfer while paused");
        require(ids.length <= MAX_BATCH_SIZE, "ERC721Uptick: batch too large");
        require(ids.length > 0, "ERC721Uptick: batch cannot be empty");

        // We cannot just use balanceOf to create the new tokenId because tokens
        // can be burned (destroyed), so we need a separate counter.
        uint256 len = 0;
        len = ids.length;
        for(uint i = 0 ;i < len ;i ++){
            for(uint j = i + 1; j < len; j++){
                require(ids[i] != ids[j], "ERC721Uptick: duplicate token id in batch");
            }
            // _safeMint (audit G-07): a receiver that rejects the token reverts
            // the whole batch, so mintBatch is all-or-nothing rather than
            // leaving a partially minted batch behind.
            _safeMint(to, ids[i]);
        }
    }

    /**
     * @dev Creates a new token for `to`. Its token ID will be automatically
     * assigned (and available on the emitted {IERC721-Transfer} event), and the token
     * URI autogenerated based on the base URI passed at construction.
     *
     * See {ERC721-_safeMint}.
     *
     * Requirements:
     *
     * - the caller must have the `MINTER_ROLE`.
     * - `to` must be an EOA or a contract implementing {IERC721Receiver}; a
     *   rejecting receiver reverts the whole batch.
     */
    function mintEnhanceBatch(address to, uint256[] memory ids,string memory name,string memory uri,string memory data,string memory uriHash) public virtual {
        require(
            hasRole(MINTER_ROLE, _msgSender()),
            "ERC721PresetMinterPauserAutoId: must have minter role to mint"
        );
        require(!paused(), "ERC721Pausable: token transfer while paused");
        require(ids.length <= MAX_BATCH_SIZE, "ERC721Uptick: batch too large");
        require(ids.length > 0, "ERC721Uptick: batch cannot be empty");

        // We cannot just use balanceOf to create the new tokenId because tokens
        // can be burned (destroyed), so we need a separate counter.
        uint256 len = 0;
        len = ids.length;
        for(uint i = 0 ;i < len ;i ++){
            for(uint j = i + 1; j < len; j++){
                require(ids[i] != ids[j], "ERC721Uptick: duplicate token id in batch");
            }
            _idEnhanceInfoMap[ids[i]].name = name;
            _idEnhanceInfoMap[ids[i]].uri = uri;
            _idEnhanceInfoMap[ids[i]].data = data;
            _idEnhanceInfoMap[ids[i]].uriHash = uriHash;
            // _safeMint (audit G-07): a rejecting receiver reverts the entire
            // batch, so no partial mint can survive.
            _safeMint(to, ids[i]);
            emit EnhanceInfoSet(ids[i], name, uri, uriHash);
        }
    }

    /**
     * @dev Destroys `id`. Kept for backwards compatibility with the existing
     * ABI; it now delegates to {ERC721Burnable-burn} because the project-wide
     * cleanup lives in {_burn} below.
     *
     * Requirements:
     *
     * - the caller must own the token or be an approved operator.
     */
    function burnEnhance(uint256 id) public {
        burn(id);
    }

    /**
     * @dev Clears every piece of project-specific token state whenever a token
     * is destroyed, regardless of which burn entry point was used (audit G-08).
     *
     * `ERC721Burnable.burn` previously went straight to OZ `_burn`, which left
     * `_idEnhanceInfoMap[id]` populated. Because token ids can be re-minted
     * after a burn, a later plain `mint` (which only writes `uri`) inherited the
     * previous lifetime's name/data/uriHash. Routing every burn through this
     * override keeps the id -> metadata mapping in sync with token existence:
     * no token, no metadata.
     */
    function _burn(uint256 id) internal virtual override {
        super._burn(id);
        delete _idEnhanceInfoMap[id];
    }

    /**
     * @dev Returns the class-level (contract-wide) enhancement metadata that was
     * supplied at construction. Read-only; mirrors the Cosmos NFT class fields
     * the Go module packs into the constructor.
     */
    function getClassEnhanceInfo() public view
    returns(string memory data,
        string memory description,
        bool mint_restricted,
        string memory schema,
        bool update_restricted,
        string memory uri,
        string memory uri_hash) {

        return (
        _enhanceClassInfo.data,
        _enhanceClassInfo.description,
        _enhanceClassInfo.mint_restricted,
        _enhanceClassInfo.schema,
        _enhanceClassInfo.update_restricted,
        _enhanceClassInfo.uri,
        _enhanceClassInfo.uri_hash
        );

    }

    /**
     * @dev Returns the per-token enhancement metadata. Returns empty strings for
     * a token id that does not exist or whose metadata was cleared by {_burn}
     * (audit G-08: burn must leave no residue behind).
     */
    function getNFTEnhanceInfo(uint256 id ) public  view
    returns(string memory name, string memory uri,string memory data,string memory uriHash) {

        return (
        _idEnhanceInfoMap[id].name,
        _idEnhanceInfoMap[id].uri,
        _idEnhanceInfoMap[id].data,
        _idEnhanceInfoMap[id].uriHash
        );

    }


    /**
     * @dev Pauses all token transfers.
     *
     * See {ERC721Pausable} and {Pausable-_pause}.
     *
     * Requirements:
     *
     * - the caller must have the `PAUSER_ROLE`.
     */
    function pause() public virtual {
        require(
            hasRole(PAUSER_ROLE, _msgSender()),
            "ERC721PresetMinterPauserAutoId: must have pauser role to pause"
        );
        _pause();
    }

    /**
     * @dev Unpauses all token transfers.
     *
     * See {ERC721Pausable} and {Pausable-_unpause}.
     *
     * Requirements:
     *
     * - the caller must have the `PAUSER_ROLE`.
     */
    function unpause() public virtual {
        require(
            hasRole(PAUSER_ROLE, _msgSender()),
            "ERC721PresetMinterPauserAutoId: must have pauser role to unpause"
        );
        _unpause();
    }

    function _beforeTokenTransfer(
        address from,
        address to,
        uint256 firstTokenId,
        uint256 batchSize
    ) internal virtual override(ERC721, ERC721Enumerable, ERC721Pausable) {
        super._beforeTokenTransfer(from, to, firstTokenId, batchSize);
    }

    /**
     * @dev See {IERC165-supportsInterface}.
     */
    function supportsInterface(bytes4 interfaceId)
    public
    view
    virtual
    override(AccessControlEnumerable, ERC721, ERC721Enumerable)
    returns (bool)
    {
        return super.supportsInterface(interfaceId);
    }
}
